<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IBM651-PC0BY5PB" ignored="0" name="WebTest - Factory with Data Provider test" tests="1" failures="1" timestamp="28 Oct 2018 13:25:29 GMT" time="417.466" errors="0">
  <testcase name="TestNG_Factory_DataProvider[login=login1]" time="43.689" classname="com.test.testscripts.testfactory.TestNG_Factory_DataProvider">
    <failure type="java.lang.AssertionError" message="buttonelement Next Button, by={By.id: nextBtn} not found. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: buttonelement Next Button, by={By.id: nextBtn} not found. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.simplewebframework.webelements.webBasePage.assertHTML(webBasePage.java:163)
at com.simplewebframework.webelements.webBasePage.assertElementEnabled(webBasePage.java:131)
at com.test.testscripts.testfactory.TestNG_Factory_DataProvider.testNextisEnabled(TestNG_Factory_DataProvider.java:70)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- TestNG_Factory_DataProvider[login=login1] -->
</testsuite> <!-- WebTest - Factory with Data Provider test -->
